/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.ConvertirController;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import models.Convertir;
import valida.ValidaKeyDouble;

/**
 *
 * @author Mauro
 */
public class ConvertirFrame extends javax.swing.JInternalFrame {
    private final Convertir convertir = new Convertir();
    private ConvertirController converC;
    ValidaKeyDouble valint = new ValidaKeyDouble();
    String [] Diner = convertir.getDinero();
    String [] dolar = convertir.getDolar();
    String [] cordoba = convertir.getCordoba();
    String [] euro = convertir.getEuro();
    
    
    public ConvertirFrame() {
        initComponents();
        setTitle("Conversor de Monedas");
        ComboT();
        calendario();
        keyConytoller();
        setupController();
        
    }
    public void setupController(){
        converC = new ConvertirController(this);
        Conv.addActionListener(converC);
    }
    public void keyConytoller(){
        MontoT.setEditable(false);
        MontoD.setEditable(false);
        ComboDeseo.setEditable(false);
        MontoT.addKeyListener(new ValidaKeyDouble());
    }
    public void calendario(){
        Calendar calendar = Calendar.getInstance();
        String year = String.valueOf(calendar.get(Calendar.YEAR)); 
        String month = String.valueOf(calendar.get(Calendar.MONTH)+1);
        String day = String.valueOf(calendar.get(Calendar.DAY_OF_MONTH));
        Calen.setText(day+"/"+month+"/"+year);
    }
    
    public void getdato(){
        String numero = String.valueOf(verificar());
        MontoD.setText(numero);
    }
    
    public void ComboT (){
        for (String estandar : Diner  ) {
            ComboTengo.addItem(estandar);
        }
        
        ComboTengo.setSelectedIndex(-1);
        ComboTengo.setSelectedItem(null);
    }
        
    public String [] selectComboD (){
        String [] recado = null;
        if(ComboTengo.getSelectedItem().toString().equals("Cordoba")){
            recado = cordoba;
        }else if(ComboTengo.getSelectedItem().toString().equals("Dolar")){
            recado = dolar;
        }else if(ComboTengo.getSelectedItem().toString().equals("Euro")){
            recado = euro;
        }
        return recado;
    }
    
    public double verificar (){
        double montt = Double.parseDouble(MontoT.getText());
        double montd = 0; 
        String tengo = ComboTengo.getSelectedItem().toString();
        String deseo =  ComboDeseo.getSelectedItem().toString();    
        if(tengo.equals("Cordoba")&& deseo.equals("Dolar")){
            montd = montt * 0.02853;
        }else if(tengo.equals("Cordoba")&& deseo.equals("Euro")){
            montd = montt * 0.02344;
        }else if(tengo.equals("Dolar")&& deseo.equals("Cordoba")){
            montd = montt * 35.0472;
        }else if(tengo.equals("Dolar")&& deseo.equals("Euro")){
            montd = montt * 0.8215;
        }else if(tengo.equals("Euro")&& deseo.equals("Cordoba")){
            montd = montt * 42.6579;
        }else if(tengo.equals("Euro")&& deseo.equals("Dolar")){
            montd = montt * 1.2171;
        }
        
        return montd;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboTengo = new javax.swing.JComboBox<>();
        ComboDeseo = new javax.swing.JComboBox<>();
        MontoT = new javax.swing.JTextField();
        MontoD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Conv = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);

        Calen.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Calen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Moneda que Tengo");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Moneda que Deseo");

        ComboTengo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTengoItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Monto");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Monto");

        Conv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Conv.setText("Convertir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(Calen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(Conv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MontoT)
                            .addComponent(ComboTengo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(ComboDeseo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MontoD)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Calen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboTengo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboDeseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MontoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MontoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Conv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboTengoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTengoItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            ComboDeseo.setModel(new DefaultComboBoxModel(selectComboD()));    
        }
        MontoT.setEditable(true);
        ComboDeseo.setSelectedIndex(-1);
        ComboDeseo.setSelectedItem(null);
    }//GEN-LAST:event_ComboTengoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calen;
    private javax.swing.JComboBox<String> ComboDeseo;
    private javax.swing.JComboBox<String> ComboTengo;
    private javax.swing.JButton Conv;
    private javax.swing.JTextField MontoD;
    private javax.swing.JTextField MontoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
