/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.DepaController;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Depa;

/**
 *
 * @author Mauro
 */
public class DepaFrame extends javax.swing.JInternalFrame {
    private DepaController depCon;
    private final Depa depa = new Depa(); 
    String [] departamento = depa.getDepartamento();
    String [] Boa = depa.getBoaco();
    String [] Cara = depa.getCarazo();
    String [] Chinan = depa.getChinandega();
    String [] Chonta = depa.getChontales();
    String [] RACCN = depa.getCostaN();
    String [] RACCS = depa.getCostaS();
    String [] Est = depa.getEstéli();
    String [] Gran = depa.getGranada();
    String [] Jino = depa.getJinotega();
    String [] Leo = depa.getLeon();
    String [] Mad = depa.getMadriz();
    String [] Mana = depa.getManagua();
    String [] Masa = depa.getMasaya();
    String [] Matag = depa.getMatagalpa();
    String [] NueS = depa.getNuevaS();
    String [] RSJ = depa.getRSanJ();
    String [] Riv = depa.getRivas();
    /**
     * Creates new form DepaFrame
     */
    public DepaFrame() {

        initComponents();
        setTitle("Formulario Nicaragua");
        ComboD();
        setupController();
        
    }
    
    public void setupController(){
        depCon = new DepaController(this);
        Nic_Button.addActionListener(depCon);
    }
    
    public void ComboD (){
        for (String prueba : departamento  ) {
            ComboDepa.addItem(prueba);
        }
        ComboDepa.setSelectedIndex(-1);
        ComboDepa.setSelectedItem(null);
    }
    
    public String [] selectMun (){
        String [] recado = null;
        if(ComboDepa.getSelectedItem().toString().equals("Boaco")){
            recado = Boa;
        }if(ComboDepa.getSelectedItem().toString().equals("Carazo")){
            recado = Cara;
        }if(ComboDepa.getSelectedItem().toString().equals("Chinandega")){
            recado = Chinan;
        }if(ComboDepa.getSelectedItem().toString().equals("Chontales")){
            recado =Chonta;
        }if(ComboDepa.getSelectedItem().toString().equals("Costa Caribe Norte")){
            recado = RACCN;
        }if(ComboDepa.getSelectedItem().toString().equals("Costa Caribe Sur")){
            recado = RACCS;
        }if(ComboDepa.getSelectedItem().toString().equals("Estelí")){
            recado = Est;
        }if(ComboDepa.getSelectedItem().toString().equals("Granada")){
            recado = Gran;
        }if(ComboDepa.getSelectedItem().toString().equals("Jinotega")){
            recado = Jino;
        }if(ComboDepa.getSelectedItem().toString().equals("León")){
            recado = Leo;
        }if(ComboDepa.getSelectedItem().toString().equals("Madriz")){
            recado = Mad;
        }if(ComboDepa.getSelectedItem().toString().equals("Managua")){
            recado = Mana;
        }if(ComboDepa.getSelectedItem().toString().equals("Masaya")){
            recado = Masa;
        }if(ComboDepa.getSelectedItem().toString().equals("Matagalpa")){
            recado = Matag;
        }if(ComboDepa.getSelectedItem().toString().equals("Nueva Segovia")){
            recado = NueS;
        }if(ComboDepa.getSelectedItem().toString().equals("Río San Juan")){
            recado = RSJ;
        }if(ComboDepa.getSelectedItem().toString().equals("Rivas")){
            recado = Riv;
        }
        return recado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboDepa = new javax.swing.JComboBox<>();
        ComboMuni = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nic_Button = new javax.swing.JButton();

        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ComboDepa.setActionCommand("");
        ComboDepa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboDepaItemStateChanged(evt);
            }
        });

        ComboMuni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboMuniItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Departamento");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Municipio");

        Nic_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nicaragua.png"))); // NOI18N
        Nic_Button.setActionCommand("Message");
        Nic_Button.setBorderPainted(false);
        Nic_Button.setContentAreaFilled(false);
        Nic_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nicaragua2.png"))); // NOI18N
        Nic_Button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nicaragua3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboDepa, 0, 184, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboMuni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(Nic_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboDepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Nic_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboDepaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboDepaItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            ComboMuni.setModel(new DefaultComboBoxModel(selectMun()));     
        }
        ComboMuni.setSelectedIndex(-1);
        ComboMuni.setSelectedItem(null);
    }//GEN-LAST:event_ComboDepaItemStateChanged

    private void ComboMuniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboMuniItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            JOptionPane.showMessageDialog(null, "Has seleccionado "+ComboDepa.getSelectedItem().toString()+", "+ComboMuni.getSelectedItem().toString());
        }
    }//GEN-LAST:event_ComboMuniItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboDepa;
    private javax.swing.JComboBox<String> ComboMuni;
    private javax.swing.JButton Nic_Button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
