/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.MainController;
import static java.awt.SystemColor.desktop;
import java.awt.Toolkit;
/**
 *
 * @author Mauro
 */
public class MainFrame extends javax.swing.JFrame {
    private MainController mc;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.mc = new MainController(this);
        initComponents();
        setIcon();
        setupController();
        setResizable(false);
        setTitle("Ejercicios de Programacion");
    }
    
    public void setupController(){
        Salir.addActionListener(mc);
        R_empleado.addActionListener(mc);
        FormuN.addActionListener(mc);
        person.addActionListener(mc);
        Conversor.addActionListener(mc);
        Config.addActionListener(mc);
        
    }
    
    public void ShowChild(javax.swing.JInternalFrame empleado,boolean maximizeFrame){
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        int xy[] = getPosition(empleado);
        desktop.add(empleado);
        empleado.setLocation(xy[0],xy[1]);
        empleado.setVisible(true);
        if(maximizeFrame){
            desktop.getDesktopManager().maximizeFrame(empleado);
        }
        setCursor(java.awt.Cursor.getDefaultCursor());
    }
    
    public int[] getPosition(javax.swing.JInternalFrame inter){
        int position[] = new int[2];
        position[0] = (desktop.getWidth()- inter.getWidth())/2;
        position[1] = (desktop.getHeight() - inter.getHeight())/2;
        return position;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplica = new javax.swing.JMenu();
        Config = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        misc = new javax.swing.JMenu();
        R_empleado = new javax.swing.JMenuItem();
        FormuN = new javax.swing.JMenuItem();
        person = new javax.swing.JMenuItem();
        Conversor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        desktop.setBackground(new java.awt.Color(107, 153, 255));
        desktop.setPreferredSize(new java.awt.Dimension(580, 387));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empleados.jpg"))); // NOI18N

        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, Short.MAX_VALUE)
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);

        aplica.setText("Aplicación");
        aplica.setToolTipText("");

        Config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        Config.setText("Configurar");
        Config.setActionCommand("configurar");
        Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigActionPerformed(evt);
            }
        });
        aplica.add(Config);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setActionCommand("exit");
        aplica.add(Salir);

        jMenuBar1.add(aplica);

        misc.setText("Misceláneos");

        R_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/concatenar.png"))); // NOI18N
        R_empleado.setText("Concatenar texto");
        R_empleado.setActionCommand("regis");
        misc.add(R_empleado);

        FormuN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.png"))); // NOI18N
        FormuN.setText("Formulario Nicaragua");
        FormuN.setActionCommand("depa");
        misc.add(FormuN);

        person.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        person.setText("Registros de personas");
        person.setActionCommand("pers");
        misc.add(person);

        Conversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/intercambiar.png"))); // NOI18N
        Conversor.setText("Conversor de Monedas");
        Conversor.setActionCommand("money");
        misc.add(Conversor);

        jMenuBar1.add(misc);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfigActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Config;
    private javax.swing.JMenuItem Conversor;
    private javax.swing.JMenuItem FormuN;
    private javax.swing.JMenuItem R_empleado;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu aplica;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu misc;
    private javax.swing.JMenuItem person;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Programacion.png")));
    }
    
}
