/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.TextoController;
import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import models.Texto;


/**
 *
 * @author Mauro
 */
public class TextoFrame extends javax.swing.JInternalFrame {
    private TextoController textoc;
    private Texto t;
    public String [] conca = new String[50];


    /**
     * Creates new form EmpleadosFrame
     */
    public TextoFrame() {
        this.conca =conca;
        setTitle("Juntar Archivos de Texto");
        initComponents();
        setupController();        
    }
    public void setupController(){
        
        textoc = new TextoController(this);
        docO1Button.addActionListener(textoc);
        docO2Button.addActionListener(textoc);
        saveButton.addActionListener(textoc);
        clearButton.addActionListener(textoc);
    }
    
    public Texto getTexto(){
        t = new Texto();
        t.setArea(area.getText());
        return t;
    }
    
    public void setTexto(String ora ){
        for (int i = 0; i < 2; i++) {
            conca [i]+=" "+ora;
            area.setText(conca[i].replaceAll("null", ""));
        }
    }
    
    public void clearTexto(){
        area.setText("");
        doc1.setText("");
        doc2.setText("");
        limpiar();
    }
    
    public void directorios(String path){
        if (directorio1().equals("")){
            doc1.setText(path);
        }else{
            doc2.setText(path);
        }
    }
    
    public String directorio1(){ 
        return doc1.getText();
    }
    
    public String directorio2(){
        return doc2.getText();
    }
    
    public void limpiar(){
        for (int i = 0; i < 2; i++) {
            conca [i]=null;
        }        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        doc1 = new javax.swing.JTextField();
        doc2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        docO1Button = new javax.swing.JButton();
        docO2Button = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        doc1.setActionCommand("");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        docO1Button.setText("...");
        docO1Button.setActionCommand("open");

        docO2Button.setText("...");
        docO2Button.setActionCommand("open");

        saveButton.setText("Guardar");
        saveButton.setActionCommand("save");

        clearButton.setText("Limpiar");
        clearButton.setActionCommand("clear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doc1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(docO1Button)
                .addGap(42, 42, 42)
                .addComponent(doc2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(docO2Button)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doc2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(docO1Button)
                        .addComponent(doc1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(docO2Button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField doc1;
    private javax.swing.JTextField doc2;
    private javax.swing.JButton docO1Button;
    private javax.swing.JButton docO2Button;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables


}
